apiVersion: v2
name: user-service
description: A Helm chart for the user microservice (Spring Boot)
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
