replicaCount: 2

image:
  repository: docker479/user-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

config:
  dbUrl: jdbc:postgresql://user-service-postgresql:5432/userdb

secrets:
  dbUser: postgres
  dbPassword: "ktq05eOpzW"
  
imagePullSecrets:
  - name: regcred
  
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: user.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []
  
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

pvc:
  enabled: true
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  size: 1Gi

postgresql:
  auth:
    username: postgres
    password: postgres
    database: userdb
  primary:
    service:
      port: 5432
jwt:
  secret:  r0zt2A61l6+9u/EjzOiNfdOzgo2F1WMAE9qD1+vY3Qc=
  expiration: "3600000"
