# manifests/argocd-user-service.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nagendrababu-ops/kubernetes-project.git
    targetRevision: main
    path: helm-charts/user-service
  destination:
    server: https://kubernetes.default.svc
    namespace: user
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

