apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: user-service
  namespaceSelector:
    matchNames:
      - user
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s

