apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  db-user: {{ .Values.secrets.dbUser }}
  db-password: {{ .Values.secrets.dbPassword }}
  jwt-secret: {{ .Values.secrets.jwtSecret }}

