apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Release.Name }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Release.Name }}
    - to:
        - namespaceSelector: {}

